### ISSUE TITLE
2024-03-12 Beta container

### ISSUE THREAD

**Issue by mchangrh** [mchangrh/NoWhatsNew#4]
The new container explicitly doesn't have a class which means we'll have to do some trickery with child selectors and hope there isn't any overlap

```css
<div><div class="_17uEBe5Ri8TMsnfELvs8-N"><div class="tECphKl9rZXG_KesmwW5r Panel">
...
```

```css
._17uEBe5Ri8TMsnfELvs8-N {
    box-sizing: border-box;
    padding: 16px 16px 0px 24px;
    position: relative;
    height: 324px;
    overflow: hidden;
    background-image: linear-gradient(to top, #171d25 0%, #2d333c 80%)
}
```
